version: '3.8'

services:
  web:
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    command: ./bin/rails server -b 0.0.0.0
    stdin_open: true
    tty: true

  db:
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mexe_development
    ports:
      - "5432:5432"

volumes:
  node_modules: 