services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3005:3000"
    volumes:
      - .:/rails
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY="QdpQKkPGrP4+0c2xl1wBo5zG/jq68iG5jsZPCisf1IQ="
      - ADMIN_EMAIL=admin@mexe.com
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: ["rails", "server", "-b", "0.0.0.0"]
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mexe_development
      - MYSQL_USER=mexe
      - MYSQL_PASSWORD=password
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
