version: '3.8'

services:
  web:
    environment:
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
    volumes:
      - .:/rails
      # - bundle_cache:/usr/local/bundle
      - node_modules:/rails/node_modules
    entrypoint: ["/rails/bin/docker-entrypoint"]
    command: ["rails", "server", "-b", "0.0.0.0"]
    stdin_open: true
    tty: true

  db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mexe_development
      - MYSQL_USER=mexe
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"

volumes:
  node_modules:
