openapi: 3.0.3
info:
  title: E-commerce API
  description: API for managing products, orders, and users in an e-commerce platform
  version: 1.0.0
servers:
  - url: /api/v1
paths:
  /products:
    get:
      summary: List all products
      operationId: listProducts
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: Number of products per page
          required: false
          schema:
            type: integer
            default: 20
        - name: category_id
          in: query
          description: Filter by category ID
          required: false
          schema:
            type: integer
        - name: brand_id
          in: query
          description: Filter by brand ID
          required: false
          schema:
            type: integer
        - name: is_active
          in: query
          description: Filter by active status
          required: false
          schema:
            type: boolean
            default: true
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: '#/components/schemas/Product'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      per_page:
                        type: integer
  /products/{id}:
    get:
      summary: Get product details
      operationId: getProduct
      parameters:
        - name: id
          in: path
          description: Product ID or slug
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDetail'
        '404':
          description: Product not found
  /orders:
    post:
      summary: Create a new order
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - items
                - payment_method
                - delivery_type
              properties:
                items:
                  type: array
                  items:
                    type: object
                    required:
                      - product_id
                      - quantity
                    properties:
                      product_id:
                        type: integer
                      variant_id:
                        type: integer
                      quantity:
                        type: integer
                        minimum: 1
                payment_method:
                  type: string
                  enum: ['credit_card', 'paypal', 'bank_transfer', 'cod']
                delivery_type:
                  type: string
                  enum: ['home', 'store_pickup']
                delivery_address:
                  type: string
                store_location:
                  type: string
                coupon_code:
                  type: string
                guest_email:
                  type: string
                guest_phone:
                  type: string
                guest_name:
                  type: string
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '422':
          description: Invalid request
  /orders/{id}:
    get:
      summary: Get order details
      operationId: getOrder
      parameters:
        - name: id
          in: path
          description: Order ID or order number
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderDetail'
        '404':
          description: Order not found
  /orders:
    get:
      summary: List all orders for the authenticated user
      operationId: listOrders
      parameters:
        - name: page
          in: query
          description: Page number for pagination
          required: false
          schema:
            type: integer
            default: 1
        - name: per_page
          in: query
          description: Number of orders per page
          required: false
          schema:
            type: integer
            default: 20
        - name: status
          in: query
          description: Filter by order status
          required: false
          schema:
            type: string
            enum: ['pending', 'processing', 'shipped', 'delivered', 'cancelled']
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  orders:
                    type: array
                    items:
                      $ref: '#/components/schemas/Order'
                  meta:
                    type: object
                    properties:
                      total:
                        type: integer
                      page:
                        type: integer
                      per_page:
                        type: integer
  /users/me:
    get:
      summary: Get authenticated user details
      operationId: getUser
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '401':
          description: Unauthorized
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        price:
          type: number
          format: float
        original_price:
          type: number
          format: float
        discount_percent:
          type: number
          format: float
        is_active:
          type: boolean
        is_featured:
          type: boolean
        is_new:
          type: boolean
        is_hot:
          type: boolean
        stock_quantity:
          type: integer
    ProductDetail:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        sku:
          type: string
        description:
          type: string
        short_description:
          type: string
        brand:
          $ref: '#/components/schemas/Brand'
        category:
          $ref: '#/components/schemas/Category'
        price:
          type: number
          format: float
        original_price:
          type: number
          format: float
        discount_percent:
          type: number
          format: float
        cost_price:
          type: number
          format: float
        weight:
          type: number
          format: float
        dimensions:
          type: string
        stock_quantity:
          type: integer
        min_stock_alert:
          type: integer
        is_active:
          type: boolean
        is_featured:
          type: boolean
        is_new:
          type: boolean
        is_hot:
          type: boolean
        is_preorder:
          type: boolean
        preorder_quantity:
          type: integer
        preorder_end_date:
          type: string
          format: date
        warranty_period:
          type: integer
        meta_title:
          type: string
        meta_description:
          type: string
        view_count:
          type: integer
        images:
          type: array
          items:
            $ref: '#/components/schemas/ProductImage'
        variants:
          type: array
          items:
            $ref: '#/components/schemas/ProductVariant'
        specifications:
          type: array
          items:
            $ref: '#/components/schemas/ProductSpecification'
    Order:
      type: object
      properties:
        id:
          type: integer
        order_number:
          type: string
        status:
          type: string
        subtotal:
          type: number
          format: float
        discount_amount:
          type: number
          format: float
        shipping_fee:
          type: number
          format: float
        tax_amount:
          type: number
          format: float
        total_amount:
          type: number
          format: float
        payment_method:
          type: string
        payment_status:
          type: string
        delivery_type:
          type: string
        created_at:
          type: string
          format: date-time
    OrderDetail:
      type: object
      properties:
        id:
          type: integer
        order_number:
          type: string
        status:
          type: string
        subtotal:
          type: number
          format: float
        discount_amount:
          type: number
          format: float
        shipping_fee:
          type: number
          format: float
        tax_amount:
          type: number
          format: float
        total_amount:
          type: number
          format: float
        payment_method:
          type: string
        payment_status:
          type: string
        delivery_type:
          type: string
        delivery_address:
          type: string
        store_location:
          type: string
        notes:
          type: string
        coupon_code:
          type: string
        coupon_discount:
          type: number
          format: float
        guest_email:
          type: string
        guest_phone:
          type: string
        guest_name:
          type: string
        created_at:
          type: string
          format: date-time
        items:
          type: array
          items:
            $ref: '#/components/schemas/OrderItem'
    User:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        full_name:
          type: string
        phone:
          type: string
        avatar:
          type: string
        date_of_birth:
          type: string
          format: date
        gender:
          type: string
        is_active:
          type: boolean
        is_verified:
          type: boolean
        email_verified_at:
          type: string
          format: date-time
        phone_verified_at:
          type: string
          format: date-time
        last_login_at:
          type: string
          format: date-time
        addresses:
          type: array
          items:
            $ref: '#/components/schemas/UserAddress'
    Brand:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
        logo:
          type: string
    Category:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        slug:
          type: string
    ProductImage:
      type: object
      properties:
        id:
          type: integer
        image_url:
          type: string
        alt_text:
          type: string
        sort_order:
          type: integer
        is_primary:
          type: boolean
    ProductVariant:
      type: object
      properties:
        id:
          type: integer
        variant_name:
          type: string
        variant_value:
          type: string
        price_adjustment:
          type: number
          format: float
        stock_quantity:
          type: integer
        sku:
          type: string
    ProductSpecification:
      type: object
      properties:
        id:
          type: integer
        spec_name:
          type: string
        spec_value:
          type: string
        sort_order:
          type: integer
    OrderItem:
      type: object
      properties:
        id:
          type: integer
        product_id:
          type: integer
        product_name:
          type: string
        product_sku:
          type: string
        product_image:
          type: string
        quantity:
          type: integer
        unit_price:
          type: number
          format: float
        total_price:
          type: number
          format: float
        variant_info:
          type: object
    UserAddress:
      type: object
      properties:
        id:
          type: integer
        full_name:
          type: string
        phone:
          type: string
        address_line1:
          type: string
        address_line2:
          type: string
        city:
          type: string
        state:
          type: string
        postal_code:
          type: string
        country:
          type: string
        is_default:
          type: boolean
        is_active:
          type: boolean
